# Generated by Django 4.0.4 on 2023-01-15 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, default="Hey There I'm using SocialWriter ", max_length=150)),
                ('avatar', models.ImageField(default='default.jpg', null=True, upload_to='blogyapp/images/profiles_img')),
                ('followers', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('personal_link', models.URLField(blank=True, null=True)),
                ('bookmarked_articles', models.ManyToManyField(blank=True, related_name='bookmarked_articles', to='blogyapp.entry')),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('liked_articles', models.ManyToManyField(blank=True, related_name='liked_articles', to='blogyapp.entry')),
                ('name', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
