# Generated by Django 4.0.4 on 2023-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_linkedin_link_profile_personal_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default="Hey There I'm using SocialWriter ", max_length=150),
        ),
    ]
