# Generated by Django 4.0.4 on 2023-01-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_articles',
        ),
    ]
