# Generated by Django 4.0.4 on 2022-06-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0005_alter_entry_introduction'),
        ('users', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogyapp.entry'),
            preserve_default=False,
        ),
    ]
