# Generated by Django 4.0.4 on 2022-06-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0005_alter_entry_introduction'),
        ('users', '0009_remove_profile_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogyapp.entry'),
        ),
    ]
