# Generated by Django 4.0.4 on 2022-06-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
    ]
