# Generated by Django 4.0.4 on 2022-06-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
