# Generated by Django 4.0.4 on 2022-06-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0011_entry_likes'),
        ('users', '0046_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_articles',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='blogyapp.entry'),
        ),
    ]
