# Generated by Django 4.0.4 on 2022-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0011_entry_likes'),
        ('users', '0047_profile_liked_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='blogyapp.entry'),
        ),
    ]
