# Generated by Django 4.0.4 on 2022-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0012_entry_bookmarks'),
        ('users', '0048_profile_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarked_articles',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_articles', to='blogyapp.entry'),
        ),
    ]
