# Generated by Django 4.0.4 on 2023-01-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_profile_bookmarks_profile_bookmarked_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', null=True, upload_to='blogyapp/images/profiles_img'),
        ),
    ]
