# Generated by Django 4.0.4 on 2022-05-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
