# Generated by Django 4.0.4 on 2023-01-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='like', max_length=50),
        ),
    ]
