# Generated by Django 4.0.4 on 2022-05-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0002_entry_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='topic',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
