# Generated by Django 4.0.4 on 2023-01-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogyapp.entry'),
        ),
    ]
