# Generated by Django 4.0.4 on 2022-06-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0003_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='introduction',
            field=models.CharField(max_length=300),
        ),
    ]
