# Generated by Django 4.0.4 on 2022-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0004_alter_entry_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='introduction',
            field=models.CharField(max_length=600),
        ),
    ]
