# Generated by Django 4.0.4 on 2022-06-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_posts'),
        ('blogyapp', '0005_alter_entry_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
