# Generated by Django 4.0.4 on 2022-06-16 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_date_created'),
        ('blogyapp', '0006_entry_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='commenter',
        ),
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
