# Generated by Django 4.0.4 on 2022-06-06 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0007_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
