# Generated by Django 4.0.4 on 2022-06-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0007_remove_comments_commenter_comments_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
