# Generated by Django 4.0.4 on 2022-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0008_alter_entry_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
