# Generated by Django 4.0.4 on 2022-06-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0010_alter_entry_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
