# Generated by Django 4.0.4 on 2022-06-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0011_entry_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bookmarks',
            field=models.IntegerField(default=0),
        ),
    ]
