# Generated by Django 4.0.4 on 2022-06-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0012_entry_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
