# Generated by Django 4.0.4 on 2022-07-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0013_entry_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=60),
        ),
    ]
