# Generated by Django 4.0.4 on 2022-12-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0014_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='blogyapp.entry'),
        ),
    ]
