# Generated by Django 4.0.4 on 2023-01-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0015_alter_comments_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AlterField(
            model_name='entry',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
