# Generated by Django 4.0.4 on 2023-01-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogyapp', '0016_remove_entry_topic_alter_entry_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blogyapp/images/articles_img'),
        ),
    ]
